# Tensor Operations Classwork

Task 1 — Create and Inspect
Create a tensor of shape (3, 3) filled with random numbers. Print its shape, data type and number of dimensions.  

Task 2 — Basic Operations
Create two tensors of shape (2, 3) and perform addition, subtraction and multiplication on them. Print all three results.

Task 3 — Medical Context
Create a tensor that represents a 5x5 grayscale image patch with pixel values between 0 and 255. Normalize it to values between 0 and 1 by dividing by 255. Print before and after.  

Task 4 — Reshaping
Create a 1D tensor with 12 elements. Reshape it into shape (3, 4) then reshape again into (2, 6). Print all three shapes.  

Task 5 — Aggregation
Create a tensor of shape (4, 4) with random values. Find and print the minimum, maximum, mean and sum of all values.  

Task 6 — Medical Context
Create a tensor representing 3 chest X-ray images each of size 64x64 pixels — shape should be (3, 64, 64). Print the shape and calculate the mean pixel value across all three images.

In [3]:
import torch
import numpy as np

In [22]:
# Task 1

x = torch.randint(0,6,(3,3))
print(x)

print("Tensor Shape is:", x.shape)
print("Tensor data type is:", x.dtype)
print("Number of dimension in tensor is:", x.ndim)

tensor([[1, 5, 4],
        [1, 1, 3],
        [0, 0, 5]])
Tensor Shape is: torch.Size([3, 3])
Tensor data type is: torch.int64
Number of dimension in tensor is: 2


In [31]:

# Task 2

a = torch.randint(0,6,(2,3))
b = torch.randint(0,6,(2,3))

add = a.add(b)
subtract = a.subtract(b)
multiply = a.multiply(b)

print("Addition Tensor is =",add)
print("Subtraction Tensor is =",subtract)
print("Multiplication Tensor is =",multiply)

Addition Tensor is = tensor([[ 5,  6, 10],
        [ 6,  7,  3]])
Subtraction Tensor is = tensor([[-5,  0,  0],
        [ 2, -1, -1]])
Multiplication Tensor is = tensor([[ 0,  9, 25],
        [ 8, 12,  2]])


In [55]:
z.shape

torch.Size([5, 5])

In [39]:

#Task 3

z = torch.randint(0,256,(5,5))

y = z.divide(255)
print(z)
print(y)

tensor([[219,  28, 159, 198,  91],
        [106,  51, 119, 182, 181],
        [121,  89,  26, 192,   4],
        [228,  71, 159, 131,  16],
        [177,  36, 226, 199,  69]])
tensor([[0.8588, 0.1098, 0.6235, 0.7765, 0.3569],
        [0.4157, 0.2000, 0.4667, 0.7137, 0.7098],
        [0.4745, 0.3490, 0.1020, 0.7529, 0.0157],
        [0.8941, 0.2784, 0.6235, 0.5137, 0.0627],
        [0.6941, 0.1412, 0.8863, 0.7804, 0.2706]])


In [42]:

# Task 4
c = torch.tensor([1,2,3,4,5,6,7,8,9,10,11,12])

d = c.reshape(3,4)
e= c.reshape(2,6)

print(c)
print(d)
print(e)

tensor([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12])
tensor([[ 1,  2,  3,  4],
        [ 5,  6,  7,  8],
        [ 9, 10, 11, 12]])
tensor([[ 1,  2,  3,  4,  5,  6],
        [ 7,  8,  9, 10, 11, 12]])


In [54]:

#Task 5

m = torch.randint(0,8,(4,4))
print(m)

mini = m.min()
print(mini)

maxi = m.max()
print(maxi)

m_float = m.type(torch.float32)
meann = m_float.mean()
print(meann)


total = m.sum()
print(total)

tensor([[2, 2, 4, 2],
        [7, 0, 6, 1],
        [3, 1, 3, 7],
        [4, 1, 2, 3]])
tensor(0)
tensor(7)
tensor(3.)
tensor(48)


In [61]:

# Task 6

q = torch.randint(0,256,(3,64,64), dtype=torch.uint8)


torch.Size([3, 64, 64])